name: Update Key Automatically
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-key:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo $(openssl rand -hex 16) > key.txt

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add key.txt
          git commit -m "Auto-update key"
          git push origin main
