name: Update Keys Automatically
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  NUM_KEYS: 1  
jobs:
  update-keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          for i in $(seq 1 $NUM_KEYS); do
            echo $(openssl rand -hex 16) > key$i.txt
          done

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add key*.txt
          git diff --cached --quiet || (git commit -m "Auto-update keys" && git push origin main)
